### ISSUE TITLE
How to install on ubuntu

### ISSUE THREAD

**Issue by bierzineo** [aswathkk/dotfiles#1]
Hey! I loved your config, but as a newbie to vim (I've been trying to replace my IDE) i cant really find a way to install it xD. I've put the init.vim, but nvim still doesn't look nothing like the pic... Thanks for the help!

**Comment by aswathkk** [comment]
Are you using NeoVim only?
Where did you place the *init.vim*? 
Did you run `:PlugInstall` after placing *init.vim*?
